services:
  #########################################################################
  plex:
    image: ghcr.io/hotio/plex:release-1.40.2.8395-c67dce28e
    restart: unless-stopped
    container_name: plex
    logging: *logging
    networks: [kometa, reverse_proxy]
    ports:
      - 32400:32400
      # - 1900:1900/udp
      # - 5353:5353/udp # Bound on Unraid already
      # - 8324:8324
      # - 32410:32410/udp
      # - 32412:32412/udp
      # - 32413:32413/udp
      # - 32414:32414/udp
      # - 32469:32469
    # devices:
    #   - /dev/dri:/dev/dri
    volumes:
      - ./plex/config:/config
      - plex-transcode:/transcode
      - /mnt/user/media:/data/media
    environment:
      - TZ=America/Chicago
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
      - PLEX_PASS=yes
    labels:
      - swag=enable

  #########################################################################
  sabnzbd:
    image: ghcr.io/hotio/sabnzbd:release-4.3.1
    restart: unless-stopped
    container_name: sabnzbd
    logging: *logging
    networks: [reverse_proxy]
    # ports:
    #   - 8080:8080
    volumes:
      - ./sabnzbd:/config
      - /mnt/user/media/.usenet:/data/media/.usenet
    environment:
      - TZ=America/Chicago
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
      - TP_THEME=plex
    labels:
      - swag=enable
      - swag_auth=authentik
